<#
.SYNOPSIS
    Enables mailbox auditing for non-compliant mailboxes.

.DESCRIPTION
    This script reads the non-compliant mailboxes CSV report generated by the
    M365 Assessment Toolkit and enables auditing for those mailboxes.

.PARAMETER CsvPath
    Path to the CSV file containing non-compliant mailboxes.
    Default: Latest *_NonCompliantMailboxes.csv file in the reports folder.

.PARAMETER WhatIf
    Shows what would happen if the script runs without making actual changes.

.PARAMETER Force
    Skips confirmation prompts.

.EXAMPLE
    .\Enable-MailboxAuditing.ps1
    Enables auditing for mailboxes in the latest non-compliant report.

.EXAMPLE
    .\Enable-MailboxAuditing.ps1 -CsvPath .\reports\M365Guardian_20241109_120000_NonCompliantMailboxes.csv -WhatIf
    Shows what mailboxes would have auditing enabled without making changes.

.EXAMPLE
    .\Enable-MailboxAuditing.ps1 -Force
    Enables auditing without confirmation prompts.

.NOTES
    Project: M365 Assessment Toolkit
    Repository: https://github.com/mobieus10036/m365-security-guardian
    Author: mobieus10036
    Version: 3.0.0
    Created with assistance from GitHub Copilot
    Requires: Exchange Online Management module
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory = $false)]
    [string]$CsvPath,

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

#Requires -Version 5.1

function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = 'White'
    )
    # Using Write-Information for better pipeline compatibility
    Write-Information $Message -InformationAction Continue
}

function Get-LatestNonCompliantReport {
    $reportsPath = Join-Path $PSScriptRoot 'reports'
    
    if (-not (Test-Path $reportsPath)) {
        throw "Reports folder not found at: $reportsPath"
    }

    $latestReport = Get-ChildItem -Path $reportsPath -Filter "*_NonCompliantMailboxes.csv" -File |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1

    if (-not $latestReport) {
        throw "No non-compliant mailboxes CSV report found in $reportsPath"
    }

    return $latestReport.FullName
}

try {
    Write-ColorOutput "`n╔══════════════════════════════════════════════════════════════════════╗" -Color Cyan
    Write-ColorOutput "║          Enable Mailbox Auditing - Remediation Script                ║" -Color Cyan
    Write-ColorOutput "╚══════════════════════════════════════════════════════════════════════╝`n" -Color Cyan

    # Determine CSV path
    if (-not $CsvPath) {
        Write-ColorOutput "No CSV path specified. Looking for latest non-compliant report..." -Color Yellow
        $CsvPath = Get-LatestNonCompliantReport
        Write-ColorOutput "Found: $CsvPath`n" -Color Green
    }

    # Verify file exists
    if (-not (Test-Path $CsvPath)) {
        throw "CSV file not found: $CsvPath"
    }

    # Import mailboxes
    Write-ColorOutput "Reading non-compliant mailboxes..." -Color Yellow
    $nonCompliantMailboxes = Import-Csv -Path $CsvPath

    if ($nonCompliantMailboxes.Count -eq 0) {
        Write-ColorOutput "✓ No mailboxes found in the CSV file. Nothing to do!" -Color Green
        exit 0
    }

    Write-ColorOutput "Found $($nonCompliantMailboxes.Count) mailbox(es) without auditing enabled`n" -Color Cyan

    # Check Exchange Online connection
    Write-ColorOutput "Checking Exchange Online connection..." -Color Yellow
    try {
        $null = Get-OrganizationConfig -ErrorAction Stop
        Write-ColorOutput "✓ Connected to Exchange Online`n" -Color Green
    }
    catch {
        Write-ColorOutput "✗ Not connected to Exchange Online" -Color Red
        Write-ColorOutput "Please run: Connect-ExchangeOnline" -Color Yellow
        exit 1
    }

    # Display mailboxes to be processed
    Write-ColorOutput "Mailboxes to enable auditing:" -Color White
    Write-ColorOutput ("─" * 70) -Color Gray
    $nonCompliantMailboxes | ForEach-Object {
        Write-ColorOutput "  • $($_.UserPrincipalName) - $($_.DisplayName)" -Color White
    }
    Write-ColorOutput ("─" * 70) -Color Gray

    # Confirm action
    if (-not $Force -and -not $WhatIfPreference) {
        Write-ColorOutput "`nThis will enable mailbox auditing for $($nonCompliantMailboxes.Count) mailbox(es)." -Color Yellow
        $confirmation = Read-Host "Do you want to proceed? (Y/N)"
        
        if ($confirmation -ne 'Y' -and $confirmation -ne 'y') {
            Write-ColorOutput "`nOperation cancelled by user." -Color Yellow
            exit 0
        }
    }

    Write-ColorOutput "`nEnabling mailbox auditing..." -Color Yellow
    
    $successCount = 0
    $failureCount = 0
    $errors = @()

    foreach ($mailbox in $nonCompliantMailboxes) {
        $upn = $mailbox.UserPrincipalName
        
        try {
            if ($PSCmdlet.ShouldProcess($upn, "Enable mailbox auditing")) {
                Set-Mailbox -Identity $upn -AuditEnabled $true -ErrorAction Stop
                Write-ColorOutput "  ✓ $upn" -Color Green
                $successCount++
            }
        }
        catch {
            Write-ColorOutput "  ✗ $upn - Error: $_" -Color Red
            $failureCount++
            $errors += [PSCustomObject]@{
                UserPrincipalName = $upn
                Error = $_.Exception.Message
            }
        }
    }

    # Summary
    Write-ColorOutput "`n╔══════════════════════════════════════════════════════════════════════╗" -Color Green
    Write-ColorOutput "║                         Operation Complete                            ║" -Color Green
    Write-ColorOutput "╚══════════════════════════════════════════════════════════════════════╝" -Color Green
    
    Write-ColorOutput "`nResults:" -Color White
    Write-ColorOutput "  ✓ Successfully enabled: $successCount" -Color Green
    
    if ($failureCount -gt 0) {
        Write-ColorOutput "  ✗ Failed: $failureCount" -Color Red
        
        # Export errors to CSV
        $errorCsvPath = $CsvPath -replace '.csv$', '_Errors.csv'
        $errors | Export-Csv -Path $errorCsvPath -NoTypeInformation -Encoding UTF8
        Write-ColorOutput "`n  Error details exported to: $errorCsvPath" -Color Yellow
    }

    Write-ColorOutput "`nVerification:" -Color White
    Write-ColorOutput "  Run this command to verify changes:" -Color Gray
    Write-ColorOutput "  Get-EXOMailbox -ResultSize Unlimited | Where-Object { -not `$_.AuditEnabled } | Select-Object UserPrincipalName, DisplayName, AuditEnabled`n" -Color Cyan

}
catch {
    Write-ColorOutput "`n✗ ERROR: $_" -Color Red
    Write-ColorOutput $_.ScriptStackTrace -Color Red
    exit 1
}
